name: Deploy build to GitHub Pages

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get branch name
        id: branch
        run: echo "VERSION=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v4.4.0

      - run: npm ci
      - run: npm run build

      - name: Checkout github-pages
        uses: actions/checkout@v4.2.2
        with:
          ref: github-pages
          path: github-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy build to version folder
        run: |
          mkdir -p github-pages/${{ steps.branch.outputs.VERSION }}
          cp -r dist/${{ steps.branch.outputs.VERSION }}/* github-pages/${{ steps.branch.outputs.VERSION }}/

      - name: Commit and push
        run: |
          cd github-pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "deploy ${{ steps.branch.outputs.VERSION }}"
          git push